imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@OpiumBundle/Resources/config/services.xml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de
    database_host: dbs17.informatik.uos.de
    database_port: 5432
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: opium
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    #translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: OpiumBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    service:
        mailer: fos_user.mailer.noop
        user_manager: pugx_user_manager

# MopaBootstrapBundle Configuration
mopa_bootstrap:
    form:
        show_legend: false
    menu: ~

# PUGXMultiUserBundle Configuration
pugx_multi_user:
    users:
        student:
            entity:
              class: OpiumBundle\Entity\Student
    #          factory:
            profile:
                form:
                    type: OpiumBundle\Form\Type\ProfileStudentFormType
                    name: fos_user_profile_form
                    validation_groups:  [Profile, Default]
        examiner:
            entity:
                class: OpiumBundle\Entity\Examiner
            profile:
                form:
                    type: OpiumBundle\Form\Type\ProfileUserFormType
        administrator:
            entity:
                class: OpiumBundle\Entity\Administrator
            profile:
                form:
                    type: OpiumBundle\Form\Type\ProfileUserFormType
