<?php

namespace OpiumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExamParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamParticipationRepository extends EntityRepository
{
}
