<?php

namespace OpiumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends EntityRepository
{
    public function getAllExamsforExaminer($eID)
    {
        $query = $this->createQueryBuilder('e');
        return $query
            ->where('e.examiner = :exID')
            ->setParameter('exID', $eID)
            ->getQuery()
            ->getResult();

        /**
         * Wenn man sich die Datenbankaufrufe nun ansieht stellt man fest, dasss sehr viele
         * einzelne Abfragen gemacht werden.
         * Habe es deshalb mit:
         * ->addSelect('e.subject', 'e.room', 'e.date', 'e.duration', 'e.type', 'e.appointment','e.semester_id','e.id')
         * versucht, dies hat aber nur zu Fehlern gefürht
         */
    }
}
