<?php

namespace OpiumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SemesterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemesterRepository extends EntityRepository
{
}
