<?php

namespace OpiumBundle\Repository;

use Doctrine\ORM\EntityRepository;
use OpiumBundle\Entity\ExamParticipation;

/**
 * StudentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
    /**
     * Selects all Students which have the $examID in Participations
     */
    public function getAllStudensForExamID($examID)
    {
        $query = $this->createQueryBuilder('s');
        return $query
            ->addSelect('ep')
            ->join('s.examParticipations', 'ep')
            ->where('ep.exam = (:eID)')
            ->setParameter('eID', $examID)
            ->getQuery()
            ->getResult();
    }
}
