<?php

namespace OpiumBundle\Repository;

use Doctrine\ORM\EntityRepository;
use OpiumBundle\Entity\User;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends EntityRepository
{
    public function findBySemesterId($semester, $user)
    {
        $qb= $this->createQueryBuilder('es');
        return $qb
            ->addSelect('s')
            ->addSelect('e')
            ->addSelect('r')
            ->addSelect('b')
            ->addSelect('ep')
            ->leftJoin('es.examParticipations', 'ep' , Join::WITH, $qb->expr()->eq('ep.student', ':user'))
            ->Join('es.room','r')
            ->Join('r.building','b')
            ->Join('es.examiner', 'e')
            ->Join('es.semester','s')
            ->where('es.semester = :SemID')
            ->setParameter('SemID', $semester->getID())
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
    public function findByExaminerId(User $user)
    {
        $qb = $this->createQueryBuilder('e');
        return $qb
            ->addSelect('r')
            ->addSelect('b')
            ->addSelect('s')
            ->join('e.semester', 's')
            ->leftJoin('e.room', 'r')
            ->join('r.building', 'b')
            ->where($qb->expr()->eq('e.examiner', ':id'))
            ->setParameter('id', $user->getId())
            ->getQuery()
            ->getResult();
    }
}
