<?php

namespace OpiumBundle\Repository;

use Doctrine\ORM\EntityRepository;
use OpiumBundle\Entity\User;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ExamParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamParticipationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findExPaByExamAndStudent($exam, $Student)
    {
        $qb= $this->createQueryBuilder('ep');
        return $qb
            ->where('ep.student = :Stud')
            ->andwhere('ep.exam = :Exam')
            ->setParameter('Stud', $Student)
            ->setParameter('Exam', $exam)
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }

    public function findExPaByStudent($Student)
    {
        $qb= $this->createQueryBuilder('ep');
        return $qb
            ->where('ep.student = :Stud')
            ->setParameter('Stud', $Student)
            ->getQuery()
            ->getResult();
    }
}
